apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: chronicles
spec:
  environments:
    - name: test
      build:
        from: TEST
    - name: prod
      build:
        from: PROD
  components:
    - name: web
      publicPort: http
      ports:
        - name: http
          port: 3000